### ISSUE TITLE
Pip install not working

### ISSUE THREAD

**Issue by daviddavo** [mmngreco/IneqPy#30]
It tries to access README.rst but it doesn't exist anymore

```
$ pip install --user ineqpy
Collecting ineqpy
  Using cached IneqPy-0.0.1.tar.gz (7.2 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-8e3n7tl6/ineqpy_4e179b93001447a48679da7bd395db70/setup.py", line 3, in <module>
          description = open('README.rst').readlines()
      FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by mmngreco** [comment]
Hi @daviddavo, thank you for opening this. Yes, I have to work on fixing the pypi upload process for the moment you can try the readme's suggestion: 

`pip install git+https://github.com/mmngreco/IneqPy.git`


Let me know if you find some problems with this.
